### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by yx199912** [60late/vite-plugin-minipic#1]
vite版本2.5.2

![DC4F4F~1](https://github.com/60late/vite-plugin-minipic/assets/95034376/8b5f69ce-8b0c-46d7-99a7-3fed8aa945b9)

**Comment by 60late** [comment]
在你项目的package.json中加入以下代码可以解决问题：
`"type": "module",`
因为目前chalk,boxen等几个依赖包最新的版本都是用的es module的原因

**Comment by yx199912** [comment]
好的谢谢
