### ISSUE TITLE
run buid 报错Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yunyingchen** [60late/vite-plugin-minipic#10]
![image](https://github.com/60late/vite-plugin-minipic/assets/30464962/02cb2177-af6b-43c1-885e-f886d8561217)

**Comment by 60late** [comment]
尝试再次运行后试试是否不再报错
如果再次运行后不再报错说明这应该是一个bug

**Comment by yunyingchen** [comment]
试了很多次了，都报同一个错

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月17日 15:18 |
| 收件人 | 60late/vite-plugin-minipic ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [60late/vite-plugin-minipic] run buid 报错Error: ENOENT: no such file or directory (Issue #10) |

尝试再次运行后试试是否不再报错
如果再次运行后不再报错说明这应该是一个bug

**Comment by qyh214** [comment]
我也遇到了类似问题，是不是因为我的项目是electron-vite，其存放png的位置和普通vite项目不同导致的？

**Comment by 60late** [comment]
这看起来像是一个bug，应该是由于目录无权限或者是资源目录与普通VITE目录不同造成的。
这个问题将在下个版本得到修复

**Comment by itmanyong** [comment]
期待这个问题修复+1

**Comment by chinahnjlk** [comment]
期待这个issues 尽快修复

**Comment by 60late** [comment]
@qyh214  @yunyingchen  @chinahnjlk @itmanyong  发布了v1.1.3版本，请升级到最新版后进行尝试。
看起来是非标准项目存放资源文件夹不同导致的，在diskcache写入文件时没有进行路径保护。
目前加了相关逻辑，可以试一下能否正常使用。

**Comment by qyh214** [comment]
确认没有问题了，可正常压缩，另外压缩比很强啊
![QQ截图20240706231501](https://github.com/60late/vite-plugin-minipic/assets/3896160/f3cd263a-ff91-424a-9d13-e4ba311061a2)
作为对比，本包没有修复前，用的临时替代
![QQ截图20240706231521](https://github.com/60late/vite-plugin-minipic/assets/3896160/c41a531b-2317-4bd9-b940-9aec1068dfae)

**Comment by 60late** [comment]
> 确认没有问题了，可正常压缩，另外压缩比很强啊 ![QQ截图20240706231501](https://private-user-images.githubusercontent.com/3896160/346282289-f3cd263a-ff91-424a-9d13-e4ba311061a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTk0NDAsIm5iZiI6MTcyMDM1OTE0MCwicGF0aCI6Ii8zODk2MTYwLzM0NjI4MjI4OS1mM2NkMjYzYS1mZjkxLTQyNGEtOWQxMy1lNGJhMzExMDYxYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTMzMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODcwMTJmMWM0YTNlNDU2ZDIxNGEzNjM3NDBkMDZhMDkwMjNhZTljMjQ3YmY4OWVhNWJiMzczM2E5ZGQxYzFhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H1EbgEdXOGBFDI-Zq5Je2gG_qbT_fVQD3Ghg1tqBuSo) 作为对比，本包没有修复前，用的临时替代 ![QQ截图20240706231521](https://private-user-images.githubusercontent.com/3896160/346282313-c41a531b-2317-4bd9-b940-9aec1068dfae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTk0NDAsIm5iZiI6MTcyMDM1OTE0MCwicGF0aCI6Ii8zODk2MTYwLzM0NjI4MjMxMy1jNDFhNTMxYi0yMzE3LTRiZDktYjk0MC05YWVjMTA2OGRmYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTMzMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyOTc4YWRhNzM4ZWVlYjNhZjFkNmMzMzdlMjJjMDcxMGVjN2IyYzhlM2RlZWJjN2E2M2RjODZjOTU3N2ZhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.viUVlUQXyzpfaWrKWGpm8gdz7-Q6OaU3GTuAuuodreU)

感谢反馈，此issue先关闭了。
