### ISSUE TITLE
Windows 运行 npm run build 报错

### ISSUE THREAD

**Issue by chinahnjlk** [60late/vite-plugin-minipic#11]
windows 环境运行npm run build 包以下图片错误

![微信图片_20240628143723](https://github.com/60late/vite-plugin-minipic/assets/31790940/d32ea718-25d8-4af9-a1cf-a902596b56f3)

**Comment by 60late** [comment]
尝试再次运行是否还会报这个错误？

**Comment by 60late** [comment]
本问题和[run buid 报错Error: ENOENT: no such file or directory #10](https://github.com/60late/vite-plugin-minipic/issues/10)问题相同，已修复。把插件版本升级至v1.1.3版本可解决
