### ISSUE TITLE
[vite-plugin-minipic]: No images are detected in this project.

### ISSUE THREAD

**Issue by MonkeysKing-6657** [60late/vite-plugin-minipic#14]
"vite-plugin-minipic": "^1.2.0",
新增图片，jenkins打包出现 
需要删除缓存才可以解决
![image](https://github.com/user-attachments/assets/fd50b2b3-8fa2-4eb6-9d6b-dd6e24c5a844)

**Comment by 60late** [comment]
出现这个提示说明没有查询到项目中存在图片，无论是从缓存中读取还是直接压缩，都应该会存在记录。
目前提供的信息有些少，无法判定是什么原因导致的。本地打包是否会出现此问题？
