### ISSUE TITLE
pnpm build报错，failed to load config from ...

### ISSUE THREAD

**Issue by gitboyzcf** [60late/vite-plugin-minipic#15]
``` 
 "vite": "^4.4.6",
 "vite-plugin-minipic": "^1.2.0",
```

![image](https://github.com/user-attachments/assets/a389df33-7e66-48d9-82c3-c5797ffd782a)

**Comment by 60late** [comment]
这个看起来是Unplugin-icons的问题，把本插件注释掉后能正常打包吗?

**Comment by gitboyzcf** [comment]
是的 注释掉压缩图片没问题但是 为什么两者有冲突呢 ？这会导致项目中的图标不能用

**Comment by 60late** [comment]
我本地测试了一下引入Unplugin-icons后并不会对打包产生影响。
请提供更多你的项目配置信息，或者最好有能够用来复现的代码以便能够定位问题

**Comment by gitboyzcf** [comment]
https://stackblitz.com/edit/vitejs-vite-xqry8u?file=vite.config.mjs  我这边重现了这个错误 麻烦看下

**Comment by 60late** [comment]
<img width="504" alt="image" src="https://github.com/user-attachments/assets/e990dfd4-210d-4e04-87e6-7d268a88f887">
你好，看了你的代码，和本插件没有关系。应该是因为在mjs文件中使用了require的写法导致的，请检查一下相关插件的正确引入方式哈

**Comment by gitboyzcf** [comment]
好的👌 谢谢
