### ISSUE TITLE
图片格式转换，引入问题

### ISSUE THREAD

**Issue by Herousi** [60late/vite-plugin-minipic#3]
图片格式转换后，打包后，引入的仍然是转换前的格式
![image](https://github.com/60late/vite-plugin-minipic/assets/38880599/172400b0-e494-42fc-bb64-f96dec52ae68)
![image](https://github.com/60late/vite-plugin-minipic/assets/38880599/c575ecbb-cc2e-4fc8-8af5-457eb739cfc1)

**Comment by 60late** [comment]
麻烦提供一下以下信息
1.使用的本插件版本
2.图片的存放路径

**Comment by 60late** [comment]
> 图片格式转换后，打包后，引入的仍然是转换前的格式 ![image](https://user-images.githubusercontent.com/38880599/284453602-172400b0-e494-42fc-bb64-f96dec52ae68.png) ![image](https://user-images.githubusercontent.com/38880599/284453744-c575ecbb-cc2e-4fc8-8af5-457eb739cfc1.png)

尝试将本插件升级到最新版本，v0.2以前的版本会有一点问题，最新版本本地测了一下没有复现这个问题
