### ISSUE TITLE
pnpm 安装 插件成功 但是内部sharp并没有下载

### ISSUE THREAD

**Issue by wuxingxi888** [60late/vite-plugin-minipic#4]
pnpm install vite-plugin-minipic -D  安装成功  版本号显示  "vite-plugin-minipic": "^1.0.9",

**Comment by 60late** [comment]
你好，目前v1.0及以上版本都是被[错误上传]的版本，请不要使用.
目前可用v0.2.1版本，后续会尝试修复错误上传的问题

**Comment by 60late** [comment]
> 你好，目前v1.0及以上版本都是被[错误上传]的版本，请不要使用. 目前可用v0.2.1版本，后续会尝试修复错误上传的问题

目前v1.1.2及以上版本已可正常使用
