### ISSUE TITLE
打包时未能识别到图片

### ISSUE THREAD

**Issue by dddepg** [60late/vite-plugin-minipic#5]
大佬好，我在项目中使用您的插件时出现了这个问题：
在我的项目中存在如图所示的图片：

![image](https://github.com/60late/vite-plugin-minipic/assets/52941559/1a318314-9175-4bbc-b862-e7f8d854ad55)

我通过一个 hook 来拼接图片 url:

```js
const getImageUrl = (url, prefix = '') => {
  return `/imgs/${prefix ? `${prefix}/` : ''}${url}`
}
```

在 vite.config.js 中进行如下设置：

```js
export default defineConfig({
  plugins: [
    vue(),
    minipic({
      sharpOptions: {
        png: {
          quality: 70,
          compressionLevel: 7
        }
      },
      cache: false,
    }), // 压缩图片插件
    ...other plugins
  ]
  ...other setting
})
```

但是当我执行 build 之后，控制台显示项目中未发现图片：

![image](https://github.com/60late/vite-plugin-minipic/assets/52941559/ac9d70b1-558a-46e3-a829-f2074bf4eaae)

**Comment by 60late** [comment]
你好，目前压缩时对 public 文件下的资源压缩存在 bug，已查明原因，将在下一个版本中修复
可以考虑暂时将 public 文件夹下的资源放到 src/assets/ 目录下
感谢你的issue

**Comment by 60late** [comment]
你好，目前对仓库进行了重构，增加了public文件夹下内容的压缩，并且修复了目前已知的一些问题，
把本插件升级至V1.1.0后再试试

**Comment by dddepg** [comment]
目前已升级至 1.1.0，但是使用时发现一些奇怪的路径问题：

![image](https://github.com/60late/vite-plugin-minipic/assets/52941559/2e21edcc-a0eb-4fc6-8e6b-46837762930b)

如下图报错所示，插件似乎并没有去寻找 `/public` 下的图片文件，反倒是在寻找 `node_modules/.cache/public` 下的图片文件

![image](https://github.com/60late/vite-plugin-minipic/assets/52941559/a177c870-c0b6-4248-86e2-ba6f54eda7e8)

因此我将我的 public 文件夹复制了一份到 `node_modules/.cache` 目录下，此时插件可以正常获取到全部图片：

![image](https://github.com/60late/vite-plugin-minipic/assets/52941559/7b5ce0b4-cef0-4e0c-85b5-756a8288bba9)

但是我对比了一下图片大小，发现插件似乎仅将 `node_modules/.cache` 目录下的图片进行了处理，并没有将其输出到 `dist` 文件夹中。

考虑到 `.cache` 文件夹中的文件似乎是之前通过  `import xxx from '@/src/assect/xxx.png` 方式引入的图片，旧版本插件的输出缓存是否对新版本插件的判断产生了一些影响？

**Comment by 60late** [comment]
插件会读取public目录下所有内容，无论是否开启cache模式都会存一份压缩后的备份在`node_modules/.cache `目录下。

目前无法复现你的问题，可以尝试以下操作：
1.升级插件至v1.1.1版本，此版本修复了win和mac文件分割线不同的问题
2.删除`node_modules/.cache `文件夹，再次运行打包尝试

**Comment by dddepg** [comment]
升级插件至v1.1.1版本后插件不再报错
