### ISSUE TITLE
开启sourcemap的情况下会报错

### ISSUE THREAD

**Issue by fan776783** [60late/vite-plugin-minipic#7]
<img width="649" alt="image" src="https://github.com/60late/vite-plugin-minipic/assets/23044276/7d91dd5c-ffeb-43e8-ad59-3625578e0aa0">
fileExt判断逻辑有瑕疵，会把.js.map文件判断成js，同时map文件读不到code，导致replaceMultipleValues方法入参inputString为underfined

**Comment by 60late** [comment]
感谢你的issue，这确实是一个问题，这个bug会在下一个版本中修复

**Comment by 60late** [comment]
你好，问题已修复，请将版本升级至1.1.2查看效果

**Comment by fan776783** [comment]
1.1.2版本验证没问题了
