### ISSUE TITLE
添加之后并没有起效

### ISSUE THREAD

**Issue by LiDevil** [60late/vite-plugin-minipic#9]
已经引入了"vite-plugin-minipic": "^1.1.2"
vite.congif.js文件也已经配置好了,打包的时候控制台也输出了压缩成功的信息，但是dist文件里面并没有被压缩，只是在node_module/.cache目录下，但是我的项目引用的还是原来的路径呀，网页上大小也没有变化
<img width="544" alt="image" src="https://github.com/60late/vite-plugin-minipic/assets/22414268/583b428f-e52d-401b-9c4f-aeeab933c581">

**Comment by 60late** [comment]
你好，我的本地无法复现你说的问题，请提供更为详细的信息
是所有的文件引用都没有改变吗？你的项目目录结构是怎样的？是否引入了其他会更改最终产物的插件？

可以尝试以下操作后试试：
1.手动删除.cache目录后重新打包
2.关闭其他会影响最终产物的进行打包测试
